### ISSUE TITLE
OpenID and OAuth2 service

### ISSUE THREAD

**Issue by PrashanthKumarM** [airavata-courses/TeamCodeRing#17]
Though our API endpoints can be authenticated through Oauth by a simple rails gem, for the class we need a new OpenID server which would server oauth tokens. Need to look at open source, easily implementable solutions to this.

**Comment by PrashanthKumarM** [comment]
@patelparth30j @Nethracs @nbisht7 I will take a look into this but if u guys have some solutions u found online, please pass it to me.

**Comment by Nethracs** [comment]
This has been changed to authenticating the front end with google OAuth2.

**Comment by Nethracs** [comment]
Authentication using google OAuth2 is implemented.
